<a href="https://colab.research.google.com/github/Aniket-Kumar-7/Pandas-Library/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
S=pd.Series([10,20,30],index=['A','B','C'])
print(S)
S[0]
S['B']

A    10
B    20
C    30
dtype: int64

/tmp/ipython-input-1070021759.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  S[0]

np.int64(20)

In [ ]:
data={'A':22,'S':23,'N':34,'M':21}
s=pd.Series(data)
s[:]+5
# s.mean()
# s.max()
# s.min()
# print(s['A'])

A    27
S    28
N    39
M    26
dtype: int64

In [ ]:
df=pd.DataFrame({
    'Name':['Aniket','Aman','Rana','Amit',"Abhay","Sushmit"],
    'Salary':[100000,10000,1000000,10000,100,2000],
    'Grade':['A','B','C','D','A','B']
})
df.head()
df.tail()
print(df.shape)
df.columns
df.info()
df.describe()
df['Name']
df[['Name']]
df.iloc[5]
df.loc[0]
df.loc[0,'Name']
df.iloc[0,0]
df[df['Grade']>'B']

(6, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Salary  6 non-null      int64
 2   Grade   6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

   Name   Salary Grade
2  Rana  1000000     C
3  Amit    10000     D

In [ ]:
X=df[['Name','Salary']].values
Y=df['Grade'].values
Y,X

(array(['A', 'B', 'C', 'D', 'A', 'B'], dtype=object),
 array([['Aniket', 100000],
        ['Aman', 10000],
        ['Rana', 1000000],
        ['Amit', 10000],
        ['Abhay', 100],
        ['Sushmit', 2000]], dtype=object))

In [ ]:
df['Salary_lakh']=df['Salary'].apply(lambda x:x/100000)
df['Salary_lakh']

0     1.000
1     0.100
2    10.000
3     0.100
4     0.001
5     0.020
Name: Salary_lakh, dtype: float64

In [ ]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

/tmp/ipython-input-2738737218.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [ ]:
df['City']=pd.Series(['Lucknow','Mumbai','Lakhimpur'])
df['City']

0      Lucknow
1       Mumbai
2    Lakhimpur
3          NaN
4          NaN
5          NaN
Name: City, dtype: object

In [ ]:
pd.read_json('/content/sample_data/anscombe.json')
pd.read_csv('/content/sample_data/mnist_test.csv',index_col=0)
df=pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head(100)
df.tail(10)
df.shape
len(df.columns)
df.info
df.describe
df['longitude'].head(10)
df[['longitude','latitude','population']].tail(10)
df.iloc[0:2].shape
df[df['population']>10000].shape
df.isnull()
# df['population'].fillna(df['population'].mean(),inplace=True)
df.sort_values('population',ascending=True)
pd.get_dummies(df['population'])

,5.0,8.0,14.0,19.0,21.0,22.0,25.0,26.0,27.0,29.0,...,7560.0,7596.0,7604.0,8152.0,8768.0,8824.0,9419.0,10877.0,11139.0,11935.0
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
import numpy as np

array=np.array([1,3,4])
labels=['A','B','C']
lis_t=['Aniket',"Kumar",20233052]
dic_t={1:10,2:20,3:30}

pd.Series(array,index=labels)
pd.Series(lis_t,index=labels)
pd.Series(dic_t)

1    10
2    20
3    30
dtype: int64

In [ ]:
d={
    'name':['Aniket','Abhay','Aman','Rana'],
    'Roll':[20233052,20233008,20233042,20233048],
    'City':['Lucknow','Varanashi','Delhi','Lakhimpur'],
    'Salary':[1000000,122000,125400,1230000]
}
df=pd.DataFrame(d,index=['A','B','C','D'])
df

     name      Roll       City   Salary
A  Aniket  20233052    Lucknow  1000000
B   Abhay  20233008  Varanashi   122000
C    Aman  20233042      Delhi   125400
D    Rana  20233048  Lakhimpur  1230000

In [ ]:
data_list=[
    ['Aniket',20233052,'Hardoi',2000000000],
    ['Aman',20233042,'Delhi',1000000],
    ['Rana',20233048,'UP',10000000],
    ['Amit',20233046,'Kanpur',12351360]
]
df=pd.DataFrame(data_list,columns=['Name','Roll','City',"Salary"],index=['A','B','C','D'])
df[['Name']]
df[['Roll','City']]
df['Profession']=['Businessman','Model',"Gamer",'Bodybuilder']
df.drop(['Profession','Name'],axis=1)
df.drop(["Profession"],axis=1,inplace=True)
df

     Name      Roll    City      Salary
A  Aniket  20233052  Hardoi  2000000000
B    Aman  20233042   Delhi     1000000
C    Rana  20233048      UP    10000000
D    Amit  20233046  Kanpur    12351360

In [ ]:
df.loc[['A']]
df.iloc[[0]]

     Name      Roll    City      Salary
A  Aniket  20233052  Hardoi  2000000000

In [ ]:
print(df)
df.iloc[[2,3]][['Name','Roll']]

     Name      Roll    City      Salary
A  Aniket  20233052  Hardoi  2000000000
B    Aman  20233042   Delhi     1000000
C    Rana  20233048      UP    10000000
D    Amit  20233046  Kanpur    12351360

   Name      Roll
C  Rana  20233048
D  Amit  20233046

In [ ]:
df['Salary']>100000
df[(df['Salary']>10000000) & (df['City']=='Hardoi')]

     Name      Roll    City      Salary
A  Aniket  20233052  Hardoi  2000000000

In [ ]:
data={
    'A':[1,3,np.nan,np.nan],
    'B':[1,3,np.nan,2],
    'C':[1,3,4,np.nan],
    "D":[1,3,np.nan,2]
}
df=pd.DataFrame(data,index=np.arange(1,5))
print(df)
df.isna().sum()
df.isna().any()
df.dropna(thresh=4)
df.dropna(subset=['C'])
df.fillna(0)
values={'A':100,'B':200,'C':300,'D':400}
df.fillna(value=values)

     A    B    C    D
1  1.0  1.0  1.0  1.0
2  3.0  3.0  3.0  3.0
3  NaN  NaN  4.0  NaN
4  NaN  2.0  NaN  2.0

       A      B      C      D
1    1.0    1.0    1.0    1.0
2    3.0    3.0    3.0    3.0
3  100.0  200.0    4.0  400.0
4  100.0    2.0  300.0    2.0

In [ ]:
students={
    "Name":['Aniket',"Aman",'Abhay','Amit'],
    'Salary':[10000000000,1000000,10000000,10000000],
    'Age':[25,27,24,23]
}

company={
    'Name':['Aniket','Aman','Amit'],
    'Comp.':['Self','Apple','Google'],
    'City':['Lucknow','Delhi','Kanpur']
}

df1=pd.DataFrame(students)
df2=pd.DataFrame(company)

pd.merge(df2,df1,on='Name',how='inner')
df3=pd.merge(df2,df1,on='Name',how='outer')
df3.fillna({'comp':'Arista','City':'Varanshi'})

     Name   Comp.      City       Salary  Age
0   Abhay     NaN  Varanshi     10000000   24
1    Aman   Apple     Delhi      1000000   27
2    Amit  Google    Kanpur     10000000   23
3  Aniket    Self   Lucknow  10000000000   25

In [ ]:
list1=[1,2,3,4]
list2=[3,4,4,5]

df1=pd.DataFrame((list1,list2))
df2=pd.DataFrame((list2,list1))
df=pd.concat((df1,df2),axis=1)
df

   0  1  2  3  0  1  2  3
0  1  2  3  4  3  4  4  5
1  3  4  4  5  1  2  3  4

In [ ]:
d1={
    'A':['Aniket','Aman','Amit']
}

d2={
    'B':[98,99,100]
}

df1=pd.DataFrame(d1)
print(df1)
df2=pd.DataFrame(d2,index=np.arange(1,4))
print(df2)
df1.join(df2)
df2.join(df1,how='outer')

        A
0  Aniket
1    Aman
2    Amit
     B
1   98
2   99
3  100

       B       A
0    NaN  Aniket
1   98.0    Aman
2   99.0    Amit
3  100.0     NaN

In [ ]:
def squareroot(number):
  return number**(.5)

In [ ]:
df2['C']=df2['B'].apply(lambda x:x**(.5))
df2

     B          C
1   98   9.899495
2   99   9.949874
3  100  10.000000

In [ ]:
df=pd.read_csv(r'/content/anime.csv')
print(df)
df.head()
df.tail()
df.shape
df.info
df.columns
df.describe
df.iloc[2]['Title']

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [ ]:
def extract_episodes(txt):
  data=""
  check=False
  for i in txt:
    if i==')':
      check=False
      return data
    if check:
      data+=i
    if i=='(':
      check=True

In [ ]:
df['Episodes']=df['Title'].apply(extract_episodes)
df['Episodes']=df['Episodes'].str.replace(' eps','')
df['Episodes']
df['Episodes']=pd.to_numeric(df['Episodes'])
df['Episodes'].mean()
df.index

RangeIndex(start=0, stop=50, step=1)

In [ ]:
df.iloc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [ ]:
def extract_time(txt):
  data=""
  check=False
  count=0
  for i in txt:
    if count==19:
      return data
    if check:
      count+=1
      data+=i
    if i==")":
      check=True
print(extract_time(df.iloc[0]['Title']))

Apr 2009 - Jul 2010

In [ ]:
df['Time']=df['Title'].apply(extract_time)
df['Time']

df['Score']==df['Score'].max()
df[df['Score']==df['Score'].max()]
print(df['Title'].value_counts().head())
df['Title'].head()
df[df['Episodes']==df['Episodes'].max()]
print(df['Episodes'].value_counts().head(5))
df.sort_values(by='Episodes',ascending=False).head(5)

Title
Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview       1
Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members                                                           1
Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members                                               1
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members                                                                1
Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview    1
Name: count, dtype: int64
Episodes
1     9
13    6
12    6
24    4
26    4
Name: count, dtype: int64

,Rank,Title,Score,Episodes,Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

In [ ]:
df

,Rank,Title,Score,Episodes,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [ ]:
def extract_months(duration):
    start, end = [x.strip() for x in duration.split("-")]
    start = pd.to_datetime(start, format="%b %Y")
    end = pd.to_datetime(end, format="%b %Y")
    return (end.year - start.year) * 12 + (end.month - start.month)

In [ ]:
df['Months']=df['Time'].apply(extract_months)
df['Months']
df[df['Months']==df["Months"].max()]

,Rank,Title,Score,Episodes,Time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110

In [ ]:
!git --version

git version 2.34.1

In [ ]:
!git config --global user.name "Aniket-Kumar-7"
!git config --global user.email "abcdkumarsai@gmail.com"

In [348]:
!git clone https://github.com/Aniket-Kumar-7/Pandas-Library.git

fatal: destination path 'Pandas-Library' already exists and is not an empty directory.

In [349]:
!git status
!git add .
!git commit -m "Added notebook from Google Colab"

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git